endpoints = [

"https://www.mr-s-leather.com/bondage-bdsm/bdsm-restraints/wrist-restraints-ankle-restraints",
"https://www.mr-s-leather.com/bondage-bdsm/bdsm-restraints/heavy-bondage-restraints",
"https://www.mr-s-leather.com/bondage-bdsm/bdsm-restraints/bondage-mitts-restraints",
"https://www.mr-s-leather.com/bondage-bdsm/gags",
"https://www.mr-s-leather.com/bondage-bdsm/blindfolds",
"https://www.mr-s-leather.com/bondage-bdsm/collars-leashes",
"https://www.mr-s-leather.com/bondage-bdsm/bondage-hoods-muzzles/leather-hoods-muzzles-masks",
"https://www.mr-s-leather.com/bondage-bdsm/bondage-hoods-muzzles/rubber-hoods-muzzles-masks",
"https://www.mr-s-leather.com/bondage-bdsm/bondage-hoods-muzzles/neoprene-hoods-muzzles-masks",
"https://www.mr-s-leather.com/bondage-bdsm/bondage-hoods-muzzles/spandex-hoods-muzzles-masks",
"https://www.mr-s-leather.com/bondage-bdsm/bondage-hoods-muzzles/muzzles",
"https://www.mr-s-leather.com/bondage-bdsm/bondage-hoods-muzzles/bdsm-masks",
"https://www.mr-s-leather.com/bondage-bdsm/bondage-hoods-muzzles/gas-masks",
"https://www.mr-s-leather.com/bondage-bdsm/sleepsacks",
"https://www.mr-s-leather.com/bondage-bdsm/straitjackets",
"https://www.mr-s-leather.com/bondage-bdsm/suspension",
"https://www.mr-s-leather.com/bondage-bdsm/fetters-usa-bondage",
"https://www.mr-s-leather.com/bondage-bdsm/iron-restraints",
"https://www.mr-s-leather.com/bondage-bdsm/handcuffs",
"https://www.mr-s-leather.com/bondage-bdsm/male-chastity",
"https://www.mr-s-leather.com/bondage-bdsm/floggers-whips/floggers",
"https://www.mr-s-leather.com/bondage-bdsm/floggers-whips/whips",
"https://www.mr-s-leather.com/bondage-bdsm/paddles-canes/paddles",
"https://www.mr-s-leather.com/bondage-bdsm/paddles-canes/canes-crops",
"https://www.mr-s-leather.com/bondage-bdsm/rope-tape",
"https://www.mr-s-leather.com/bondage-bdsm/spreader-bars",
"https://www.mr-s-leather.com/bondage-bdsm/locks-accessories",

]
